### ISSUE TITLE
tip

### ISSUE THREAD

**Issue by lushi78778** [Drincann/checker#1]
轮询这个端口压力特别大，一个学号就是一个io，我们已计划关闭接口。以避免服务器不堪压力崩溃。请谅解，谢谢。联系方式：lushi78778@outlook.com

Polling on this port is particularly stressful. One student number is an IO. We have planned to close the port. To prevent the server from collapsing under pressure. Please understand, thank you. Contact: lushi78778@outlook.com

**Comment by Drincann** [comment]
不好意思，我本来只是在班级内使用，方便班委日常工作，后来意外被更多人知道了。

实际上去年我们就一直在用类似的方式进行签到情况的检查。

不过我有个疑问，对一个读接口的低并发为什么会造成压力？请问咱们这个读接口还做了什么其他事情吗？

**Comment by Drincann** [comment]
下边夹一段英文干啥？

![B7A327129EB782CDEAD8A75011C1DB45](https://user-images.githubusercontent.com/53897259/130395576-2c4f7ca1-b993-49cd-a38c-fe9e71f860a0.jpg)

**Comment by lushi78778** [comment]
正常使用其实是没有问题的，但是你是在轮询或者并发调接口，不知你是否做过峰值qps估计，并发量其实挺高的。我看服务器日志每秒四五条差不多，这只是我平常看的。试想，30人一班，你那样是30次sql查询，不考虑sql语句本身，其实一条语句足矣。我何必要冒着服务器会崩的风险呢？ 希望理解！有兴趣可以做交流呀，qq1365803618 陆安 ***@***.*** 签名由 网易邮箱大师 定制 On 08/23/2021 13:32, 高厉害 wrote: 不好意思，我本来只是在班级内使用，方便班委日常工作，后来意外被更多人知道了。 实际上去年我们就一直在用类似的方式进行签到情况的检查。 不过我有个疑问，对一个读接口的低并发为什么会造成压力？请问咱们这个读接口还做了什么其他事情吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Drincann** [comment]
总之这个事的问题在我，给你们添麻烦了。

**Comment by Drincann** [comment]
不过每次并发 30 个简单查询，我感觉与 "冒着服务器会崩的风险" 搭不上边，除非后端的一些逻辑真的非常脆弱，如果是这样的话，那并发请求确实是一种高危操作，在 8090 端口上开放的 api 尽早关闭了比较明智。

**Comment by lushi78778** [comment]
1.十个人一起用，就是300次。您不写，就不要站着说话不腰疼。反正服务异常了也没人找您。不要用您的感觉来揣测后端逻辑。有本事您来。实现这些功能，亮出您的代码。
2.这个接口不是api，您没有被授权，这是非法调用。他从来只是让用户手动查询的。
3.您有本身有本事您也来为学校写。而不是在这里讽刺我们的代码！学生何苦嘲讽学生。

**Comment by lushi78778** [comment]
您的话很令人不舒服

**Comment by pengziyi-handsome** [comment]
@Drincann 请问你是沙壁吗？谁授权你轮询的，你有学生处领导的批准吗，你这叫非法访问，属于网络攻击构成犯罪你懂吗？自以为是的沙壁。

**Comment by super-pixel-coder** [comment]
查一个班的数据用30次sql查询？？您真的是太厉害了这样的水平也懂后台逻辑？？

**Comment by pengziyi-handsome** [comment]
![图片](https://user-images.githubusercontent.com/77147510/130419272-bd6395ae-b702-465c-b80c-7d53e4f911de.png)

**Comment by zjc1212123** [comment]
兄弟你就是传说中高厉害吗？真的好厉害呦。厉害到满面春风，春风得意，得意忘形了吧。你胆子是有多大，还敢未经学校授权，私自瞎几把搞。你可别整那左脚画六右脚七，左脚拐了右脚踢左腿拉跨右腿劈的梦幻舞步了。

**Comment by Drincann** [comment]
？

**Comment by Drincann** [comment]
我没有讽刺，兄弟们，我觉得我们一直在实事求是地讨论技术问题，而不是嘲讽什么的。

而且我很诚恳地说明了我的问题，可能我的表达方式并不好，但是在我的印象中，如果一个读操作顶不住几百的并发，然后这个接口也没有做请求限制，这确实很危险，并没有任何嘲讽的意思。

如果我的话让你们很生气，我为这个道歉，不好意思。

都是一个学校的，善意地猜测我的想法不好吗？没必要开喷。

**Comment by Drincann** [comment]
我没有讽刺，兄弟们，我一直在实事求是地讨论问题，而且我很诚恳地说明了我的问题，可能我的表达方式并不好，但是在我的印象中，如果一个读操作顶不住几百的并发，然后这个接口也没有做请求限制，这确实很危险，并没有任何嘲讽的意思。

如果我的话让你们很生气，我为这个道歉，不好意思。

都是一个学校的，善意地交流不好吗？没必要开喷。

**Comment by lushi78778** [comment]
这个接口也不是你能用的好吗？ 你根本就没有被授权。 讨论？讨论啥？ 讨论您侵权？ 陆安 ***@***.*** 签名由 网易邮箱大师 定制 On 08/23/2021 17:31, 高厉害 wrote: 我没有讽刺，兄弟们，我一直在实事求是地讨论问题，而且我很诚恳地说明了我的问题，可能我的表达方式并不好，但是在我的印象中，如果一个读操作顶不住几百的并发，然后这个接口也没有做请求限制，这确实很危险，并没有任何嘲讽的意思。 如果我的话让你们很生气，我为这个道歉，不好意思。 都是一个学校的，善意地交流不好吗？没必要开喷。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Drincann** [comment]
> 总之这个事的问题在我，给你们添麻烦了。

关于这一点我确实善意地承认了我的问题，其后的所有讨论，我都仅针对技术进行讨论，没有任何嘲讽的意思。

我一直以为我们的讨论很愉快，但貌似你们曲解了我的意思。

**Comment by lushi78778** [comment]
我本来是想跟你好好讨论，我甚至给了你我QQ。 但是你没有诚意。 明眼人都能看出来，我不多说了。 有本事摆出你的代码 陆安 ***@***.*** 签名由 网易邮箱大师 定制

**Comment by Drincann** [comment]
我热爱技术，我相信你们也热爱技术，我也以为我们一直在讨论技术。

你们说该接口准备关闭，我认为正常的读操作请求应该能很简单地抗住不低的并发量，但是你说几百并发可能会导致崩溃，这说明这个接口也许做了其他事情，我确实也很友善地在第一条回复里询问了，还发了表情包以示友善，

在这种情况下，尽早关闭（或者做请求限制）确实是一种明智的选择，我不知道这句话到底有什么嘲讽的意味在里面。

如果本部的兄弟们认为我的语气有问题，我很真诚的给你们道歉，真的不好意思。

我认为我们都是一个学校的，所以表达上很放松，确实没有任何嘲讽的意思在里面，我平常跟朋友们交流也是这样。

**Comment by Drincann** [comment]
本部的计算机系氛围比我们这好太多了，我知道你们那里竞赛强一些，所以我之前也很诚恳地请教过 Rhythm ，询问如何运营一个竞赛组织。

我希望我们可以善意地讨论技术，不希望因为一些猜测破坏了我们校区计算机系之间的关系。

**Comment by lushi78778** [comment]
要是这样揣测我的隐含之意的话，明确跟您，说这个接口不允许被调用。 你说的话只能证明你没有实战经验。 你觉得是你觉得，仅此而已。 反正是不是嘲讽你自己清楚。 刷借口视情况，最高可处三年以下有期徒刑。如有不当地方请您参见现行法律。 请自通知日起立即停止侵权行动，此为正式通告。

**Comment by Drincann** [comment]
无话可说，我的态度从一开始就一直很诚恳，也很早就承认了我的问题，请你们不要曲解我的意思。

干活了，不聊了。

**Comment by lushi78778** [comment]
后来想了想，我们有点过分。 谨此表达我最真挚的歉意 lushi78778
